version: '2'

services:
    postgres:
        container_name: bus_postgres
        build: .docker/postgres
        ports:
            - 5432:5432
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=pg01
            - POSTGRES_USER=postgres
            - POSTGRES_DB=bus
    php:
        container_name: bus_php
        build: .docker/php
        ports:
            - 9000:9000
        depends_on:
            - postgres
        environment:
             - PHP_IDE_CONFIG=serverName=localhost
        restart: always
        volumes:
            - .:/var/www/html
    web:
        container_name: bus_web
        build: .docker/web
        ports:
            - 80:80
            - 443:443
        volumes_from:
            - php
        volumes:
            - .docker/web/certs:/etc/nginx/ssl
            - .docker/web/conf.d:/etc/nginx/conf.d
        depends_on:
            - php
        links:
            - php
        restart: always
volumes:
    db_data: