system:
    resource: "@SystemBundle/Resources/config/routing.yml"
    type:        rest

app.swagger_ui:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /

app.swagger:
    path: /.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
