system_user:
    resource: SystemBundle\Controller\UserController
    type: rest
    prefix: system/user
    name_prefix: system_user_

system_token:
    resource: SystemBundle\Controller\TokenController
    type: rest
    prefix: system/token
    name_prefix: system_token_
